version: '3.3'

services:
  dalvtor:
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV}
    container_name: dalvtor
    volumes:
      - ./src:/src
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      APP_ENV: ${APP_ENV}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8001:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

